// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpcDxn2Q6Wb0Xu92DLPawDBClcMikINpU',
    appId: '1:646890206186:web:44916b1d510ccf99f17893',
    messagingSenderId: '646890206186',
    projectId: 'flutter-fire-4cd4c',
    authDomain: 'flutter-fire-4cd4c.firebaseapp.com',
    storageBucket: 'flutter-fire-4cd4c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSbcpZjS4eh_kJDeFpyQ0YrinlLure8rU',
    appId: '1:646890206186:android:1edbc50e439f0655f17893',
    messagingSenderId: '646890206186',
    projectId: 'flutter-fire-4cd4c',
    storageBucket: 'flutter-fire-4cd4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqC3J_VOEKDlv7N_JQAn3yOOobZNx0gsk',
    appId: '1:646890206186:ios:d93cb6db99fbfc86f17893',
    messagingSenderId: '646890206186',
    projectId: 'flutter-fire-4cd4c',
    storageBucket: 'flutter-fire-4cd4c.appspot.com',
    iosBundleId: 'com.gdsc.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqC3J_VOEKDlv7N_JQAn3yOOobZNx0gsk',
    appId: '1:646890206186:ios:e316f9bab52cf730f17893',
    messagingSenderId: '646890206186',
    projectId: 'flutter-fire-4cd4c',
    storageBucket: 'flutter-fire-4cd4c.appspot.com',
    iosBundleId: 'com.gdsc.myNotes.RunnerTests',
  );
}
